-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. User Tokens Table (Private)
-- Stores Google OAuth tokens. 
-- RLS: Users can only see their own tokens.
create table public.user_tokens (
  user_id uuid references auth.users not null primary key,
  google_id text,
  channel_id text,
  access_token text,
  refresh_token text,
  token_expiry timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_tokens enable row level security;

create policy "Users can view their own tokens"
  on public.user_tokens for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own tokens"
  on public.user_tokens for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own tokens"
  on public.user_tokens for update
  using ( auth.uid() = user_id );

-- 2. Reply Logs Table
-- Stores history of AI replies.
create table public.reply_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_id text,
  comment_id text,
  original_comment text,
  ai_suggestion text,
  final_reply text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.reply_logs enable row level security;

create policy "Users can view their own reply logs"
  on public.reply_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own reply logs"
  on public.reply_logs for insert
  with check ( auth.uid() = user_id );

-- 3. Usage Logs Table
-- Stores token usage for AI generation.
create table public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  input_tokens int,
  output_tokens int,
  model_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.usage_logs enable row level security;

create policy "Users can view their own usage logs"
  on public.usage_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own usage logs"
  on public.usage_logs for insert
  with check ( auth.uid() = user_id );
